# Generated by Django 3.2.8 on 2021-11-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20211107_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='сategory',
            new_name='postCategory',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
